# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_project_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProjectWindow(object):
    def setupUi(self, CreateProjectWindow):
        CreateProjectWindow.setObjectName("CreateProjectWindow")
        CreateProjectWindow.resize(400, 350)
        CreateProjectWindow.setMinimumSize(QtCore.QSize(400, 350))
        CreateProjectWindow.setMaximumSize(QtCore.QSize(400, 350))
        CreateProjectWindow.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.frame_2 = QtWidgets.QFrame(CreateProjectWindow)
        self.frame_2.setGeometry(QtCore.QRect(-20, 0, 400, 350))
        self.frame_2.setMinimumSize(QtCore.QSize(400, 350))
        self.frame_2.setMaximumSize(QtCore.QSize(400, 330))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setEnabled(True)
        self.frame.setMinimumSize(QtCore.QSize(275, 0))
        self.frame.setMaximumSize(QtCore.QSize(275, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #666;    /* Dark border for the input box */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"    padding: 5px;              /* Padding inside the input box */\n"
"    background-color: #666;    /* Same background color as the combo box */\n"
"    color: white;              /* White text color */\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.frame_7)
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(160, 0))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #666;    /* Dark border for the input box */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"    padding: 5px;              /* Padding inside the input box */\n"
"    background-color: #666;    /* Same background color as the combo box */\n"
"    color: white;              /* White text color */\n"
"}\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_2.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border: 1px solid #666;    /* Dark border for the button */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"    padding: 5px;              /* Padding inside the button */\n"
"    background-color: #ffd321;\n"
"    color: white;              /* White text color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 182, 28);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 137, 18);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame_8)
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(160, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #666;    /* Dark border for the input box */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"    padding: 5px;              /* Padding inside the input box */\n"
"    background-color: #666;    /* Same background color as the combo box */\n"
"    color: white;              /* White text color */\n"
"}\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_4.addWidget(self.lineEdit_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_3.setMinimumSize(QtCore.QSize(60, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border: 1px solid #666;    /* Dark border for the button */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"    padding: 5px;              /* Padding inside the button */\n"
"    background-color: #ffd321;\n"
"    color: white;              /* White text color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 182, 28);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 137, 18);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.frame_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setEnabled(True)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border: 1px solid #666;    /* Dark border for the button */\n"
"    border-radius: 5px;        /* Rounded corners */\n"
"    padding: 5px;              /* Padding inside the button */\n"
"    background-color: #ffd321;\n"
"    color: white;              /* White text color */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(220, 182, 28);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(170, 137, 18);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(CreateProjectWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateProjectWindow)

    def retranslateUi(self, CreateProjectWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateProjectWindow.setWindowTitle(_translate("CreateProjectWindow", "Dialog"))
        self.label.setText(_translate("CreateProjectWindow", "Project Name"))
        self.label_2.setText(_translate("CreateProjectWindow", "Original AoE2DE Folder"))
        self.pushButton_2.setText(_translate("CreateProjectWindow", "Browse"))
        self.label_3.setText(_translate("CreateProjectWindow", "Mods Folder"))
        self.pushButton_3.setText(_translate("CreateProjectWindow", "Browse"))
        self.pushButton.setText(_translate("CreateProjectWindow", "Create Project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateProjectWindow = QtWidgets.QDialog()
    ui = Ui_CreateProjectWindow()
    ui.setupUi(CreateProjectWindow)
    CreateProjectWindow.show()
    sys.exit(app.exec_())
