# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saving_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 100)
        Dialog.setMinimumSize(QtCore.QSize(450, 100))
        Dialog.setMaximumSize(QtCore.QSize(550, 100))
        Dialog.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progress_bar = QtWidgets.QProgressBar(Dialog)
        self.progress_bar.setMinimumSize(QtCore.QSize(400, 30))
        self.progress_bar.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progress_bar.setFont(font)
        self.progress_bar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #666;     /* Dark border */\n"
"    border-radius: 5px;         /* Rounded corners */\n"
"    background-color: #3a3a3a;  /* Dark background */\n"
"    text-align: center;         /* Center the percentage text */\n"
"    color: white;;               /* White text color */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(255, 211, 33);\n"
"}\n"
"")
        self.progress_bar.setProperty("value", 60)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout.addWidget(self.progress_bar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
